-- MySQL Script generated by MySQL Workbench
-- 08/20/18 20:58:57
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema download
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `download` ;

-- -----------------------------------------------------
-- Schema download
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `download` DEFAULT CHARACTER SET utf8 ;
USE `download` ;

-- -----------------------------------------------------
-- Table `download`.`download`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `download`.`download` ;

CREATE TABLE IF NOT EXISTS `download`.`download` (
  `file_name` VARCHAR(100) NOT NULL,
  `size` VARCHAR(45) NOT NULL,
  `status` DOUBLE NOT NULL,
  `url` VARCHAR(500) NOT NULL,
  `saved_path` VARCHAR(500) NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
